### ISSUE TITLE
[HELP NEEDED] I am stuck in decryption phase

### ISSUE THREAD

**Issue by drenther** [bbstilson/node-encryption#5]
I am using this approach of encryption and decryption with a Nest.js based backend and Firebase (Google Storage) as the file storage.

The files got encrypted and saved to firestore perfectly but decryption was failing with the following stack trace.

Stack Trace:
```
Error: Unsupported state or unable to authenticate data
    at Decipheriv._flush (internal/crypto/cipher.js:134:28)
    at Decipheriv.prefinish (_stream_transform.js:141:10)
    at Decipheriv.emit (events.js:198:13)
    at Decipheriv.EventEmitter.emit (domain.js:448:20)
    at prefinish (_stream_writable.js:635:14)
    at finishMaybe (_stream_writable.js:643:5)
    at endWritable (_stream_writable.js:663:3)
    at Decipheriv.Writable.end (_stream_writable.js:594:5)
    at ReadStream.onend (_stream_readable.js:655:10)
    at Object.onceWrapper (events.js:286:20)
    at ReadStream.emit (events.js:203:15)
    at ReadStream.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I have checked and the `initVect` extraction is working fine as the binary that was added during encryption and the one extracted during decryption is working fine.

Example code of the implementation - 
https://gist.github.com/drenther/7da04a226aaa68c357ce8420ecea8bff

**Comment by drenther** [comment]
Any help will be appreciated, but I can understand if you close this issue as it is not related to the repo's source code as such. Thanks in advance. :)
